// Builds app/headline-font.css: a few-kilobyte subset of Fraunces holding only the hero headline's letters,
// inlined so the headline paints in its final face with the first frame. Re-run if the headline text changes.
import { writeFileSync } from 'node:fs';

const TEXT = 'Order ahead, walk right in.';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const url = `https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,144,500;1,144,400&display=block&text=${encodeURIComponent(TEXT)}`;

const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
const faces = [...css.matchAll(/font-style: (\w+);[\s\S]*?font-weight: (\d+);[\s\S]*?src: url\(([^)]+)\)/g)];
if (faces.length !== 2) throw new Error(`expected 2 faces, got ${faces.length}\n${css}`);

let out = '/* Generated by tools/headline-font.mjs. Fraunces is licensed under the SIL Open Font License. */\n';
for (const [, style, weight, src] of faces) {
  const data = Buffer.from(await (await fetch(src)).arrayBuffer());
  console.log(style, weight, data.length, 'bytes');
  out += `@font-face {\n  font-family: 'Fraunces Headline';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: block;\n  src: url(data:font/woff2;base64,${data.toString('base64')}) format('woff2');\n}\n`;
}
writeFileSync('app/headline-font.css', out);
